export const GET_CLIENT_LIST = 'GET_CLIENT_LIST';
export const GET_CLIENT_LIST_SUCCESS = 'GET_CLIENT_LIST_SUCCESS';
export const GET_CLIENT_LIST_FAILED = 'GET_CLIENT_LIST_FAILED';

export const SET_ACTIVE_CLIENT = 'SET_ACTIVE_CLIENT';
export const FILTER_CLIENT_LIST = 'FILTER_CLIENT_LIST';
